services:
  devenv:
    image: ghcr.io/artemsokolov/devenv:main-latest
    pull_policy: always
    user: "${DEVENV_UID:-1000}:${DEVENV_GID:-1000}"
    group_add:
      - "${DEVENV_DOCKER_GID:-1001}"
    environment:
      - HOME=/home/${DEVENV_USER}
    volumes:
      - '${HOME}:/home/${DEVENV_USER}'
      - '/mnt:/mnt'
      - '/var/run/docker.sock:/var/run/docker.sock'
    working_dir: /home/${DEVENV_USER}
    command: >
      bash -c "
      /usr/local/bin/code tunnel user login --provider github &&
      /usr/local/bin/code tunnel --name devenv
      "
