services:
  devenv:
    image: ghcr.io/artemsokolov/devenv:main-latest
    volumes:
      - '${HOME}:/workspace'
      - '/var/run/docker.sock:/var/run/docker.sock'
    working_dir: /workspace
    command: >
      bash -c "
      /usr/local/bin/code tunnel user login --provider github &&
      /usr/local/bin/code tunnel --name devenv
      "
